// <auto-generated />
namespace nmct.ssa.labo.webshop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class basketdevice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(basketdevice));
        
        string IMigrationMetadata.Id
        {
            get { return "201503101413575_basket-device"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
